## a. Coordinate Normalization (Broadcasting)

In [1]:
import numpy as np

p = np.array([[1.0, 2.0, 10],
              [3.0, 4.0, 20],
              [5.0, 6.0, 30],
              [7.0, 8.0, 40]])

z = p[:, 2]

z_col = z[:, np.newaxis] 
p_norm = p / z_col

print(p_norm)

[[0.1        0.2        1.        ]
 [0.15       0.2        1.        ]
 [0.16666667 0.2        1.        ]
 [0.175      0.2        1.        ]]


## b. Fancy Indexing the Diagonal

In [2]:
A = np.arange(9).reshape(3, 3)

diagonal = A[[0, 1, 2], [0, 1, 2]]

print(diagonal)

[0 4 8]


## c. Finding the Closest Number

In [3]:
X = np.random.rand(10, 3)

distances = np.abs(X - 0.75)

j = np.argmin(distances, axis=1)

closest_values = X[np.arange(10), j]

print("Indices:", j)
print("Values:", closest_values)

Indices: [1 2 2 0 0 0 1 2 2 1]
Values: [0.73395611 0.56995357 0.97759146 0.71292231 0.54029927 0.52668344
 0.69630203 0.80349956 0.66992659 0.98231934]


## d. Predicting Slicing Shapes

In [4]:
x = np.empty((10, 8, 6))

idx0 = np.zeros((3, 8)).astype(int)
idx1 = np.zeros((3, 1)).astype(int)
idx2 = np.zeros((1, 1)).astype(int)

print(x[idx0, idx1, idx2].shape) 

(3, 8)


## e. Very Advanced 'as_strided'

In [6]:
from numpy.lib.stride_tricks import as_strided

x = np.arange(12, dtype=np.int32).reshape((3, 4))

row_stride, col_stride = x.strides

z = as_strided(x, 
               shape=(2, 3, 2, 2),
               strides=(row_stride, col_stride, row_stride, col_stride))

print(z)

[[[[ 0  1]
   [ 4  5]]

  [[ 1  2]
   [ 5  6]]

  [[ 2  3]
   [ 6  7]]]


 [[[ 4  5]
   [ 8  9]]

  [[ 5  6]
   [ 9 10]]

  [[ 6  7]
   [10 11]]]]
