In [ ]:
import numpy as np
from scipy import linalg

In [2]:
# a. Define matrix A
A = np.array([[1, -2, 3],
              [4,  5, 6],
              [7,  1, 9]])

# b. Define vector b
b = np.array([1, 2, 3])

# c. Solve the linear system A x = b
x = linalg.solve(A, b)
print(f"Solution x: {x}")

Solution x: [0.         0.         0.33333333]


In [3]:
# d. Check that the solution is correct
is_correct = np.allclose(A.dot(x), b)
print(f"Is the solution correct? {is_correct}")

Is the solution correct? True


In [4]:
# e. Repeat using a random 3x3 matrix B
B = np.random.rand(3, 3)
X = linalg.solve(A, B)
print(f"Solution matrix X for A X = B:\n{X}")

Solution matrix X for A X = B:
[[-0.00941977 -0.74270363 -0.29773047]
 [ 0.00200683  0.07897042 -0.03329951]
 [ 0.09694958  0.58304869  0.33363497]]


In [5]:
# f. Solve the eigenvalue problem for A
eigenvalues, eigenvectors = linalg.eig(A)
print(f"Eigenvalues:\n{eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

Eigenvalues:
[-1.13261772+0.j 10.67269524+0.j  5.45992248+0.j]
Eigenvectors:
[[-0.8215735   0.05324273  0.25636602]
 [-0.02150583  0.74309552 -0.93563185]
 [ 0.56969684  0.66706391 -0.24263037]]


In [6]:
# g. Calculate the inverse and determinant of A
A_inv = linalg.inv(A)
A_det = linalg.det(A)
print(f"Inverse of A:\n{A_inv}")
print(f"Determinant of A: {A_det:.4f}")

Inverse of A:
[[-0.59090909 -0.31818182  0.40909091]
 [-0.09090909  0.18181818 -0.09090909]
 [ 0.46969697  0.22727273 -0.1969697 ]]
Determinant of A: -66.0000


In [7]:
# h. Calculate the norm of A with different orders
norm_frob = linalg.norm(A)          # Frobenius norm
norm_1 = linalg.norm(A, 1)          # L1 norm
norm_inf = linalg.norm(A, np.inf)   # L-infinity norm
print(f"Frobenius Norm: {norm_frob:.4f}, L1 Norm: {norm_1}, L-inf Norm: {norm_inf}")

Frobenius Norm: 14.8997, L1 Norm: 18.0, L-inf Norm: 17.0
